import ../byondapi_raw/byondapi

const
    NULL* = BYOND_TYPE_NULL
    NUMBER* = BYOND_TYPE_NUMBER
    STRING* = BYOND_TYPE_STRING
    LIST* = BYOND_TYPE_LIST
    MOB* = BYOND_TYPE_MOB
    OBJ* = BYOND_TYPE_OBJ
    TURF* = BYOND_TYPE_TURF
    AREA* = BYOND_TYPE_AREA
    CLIENT* = BYOND_TYPE_CLIENT
    DBREF* = BYOND_TYPE_DBREF
    FILE* = BYOND_TYPE_FILE
    IMAGE* = BYOND_TYPE_IMAGE
    FILTER* = BYOND_TYPE_FILTER
    ICON_STATE* = BYOND_TYPE_ICON_STATE
    DATUM* = BYOND_TYPE_DATUM
    POINTER* = BYOND_TYPE_POINTER
